# Base configs
baseurl: ""
# image_fulls_loc: "/images/fulls"
# image_thumbs_loc: "/images/thumbs"
media:
  - type: youtube
    url: https://youtu.be/Y6Nox64qXw0
  - type: youtube
    url: https://youtu.be/Py9T5tPc6Ow
  - type: youtube
    url: https://youtu.be/Fr2807MvBHA
    title: "Lip Sync & Emotional Performance"
    date: "19 July 2025"
    role: "Individual Project"
    # description: >
    #   This animation is based on the iconic “I’m as mad as hell” speech from *Network (1976)*,
    #   in which news anchor Howard Beale delivers a passionate on-air breakdown, urging viewers
    #   to reject societal complacency.
    # credits:
    #   - "Audio: Scene from Network (1976)"
    #   - "Rig: Malcolm 2.0 by AnimSchool https://store.animschool.edu/product/malcolm-2-0-2/"

  - type: youtube
    url: https://youtu.be/BtX953SqPZM
  - type: youtube
    url: https://youtu.be/BeCh_Mb8BeQ
  - type: youtube
    url: https://youtu.be/EcxJp-UTuqY
  - type: youtube
    url: https://youtu.be/CPM08N48te0
  - type: youtube
    url: https://youtu.be/ik4Q4zwglyc

google_analytics: "UA-46465113-2"

# UI configs
title: "Portfolio by Andrew Gong"
subtitle: "See the world through my eyes!"
author: "Andrew Gong"
header:
 title: "Portfolio"
 subtitle: "by Andrew Gong"
footer:
 name: "Andrew Gong"
 bio: "I am a software developer and 3D animator currently studying Computer Science and Fine Arts (Animation & Moving Image) at the University of New South Wales. I specialise in combining technical and creative disciplines, with experience developing 3D applications using C++, DirectX, and Unreal Engine, alongside creating animation and assets in Maya and ZBrush."
 skills: "My background in graphics programming and computer graphics has given me a strong understanding of scripting and technical animation."
 awards: "As a two-time UNSW ADA Dean’s List recipient, I am driven by curiosity, a strong work ethic, and a commitment to continuous improvement."
web_design: "Andrew Gong"

social_urls:
  twitter: "https://www.twitter.com/rampatra_"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/andrew-gong-17a059318/"
  github: "https://github.com/Kidudeman"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
