# Base configs
baseurl: "https://Kidudeman.github.io""
# image_fulls_loc: "/images/fulls"
# image_thumbs_loc: "/images/thumbs"
media:
  - type: youtube
    url: https://youtu.be/Y6Nox64qXw0
  - type: youtube
    url: https://youtu.be/Py9T5tPc6Ow
  - type: youtube
    url: https://youtu.be/qzXHRQ69_m0
  - type: youtube
    url: https://youtu.be/Q5mPHiKrljk
  - type: youtube
    url: https://youtu.be/EcxJp-UTuqY
  - type: youtube
    url: https://youtu.be/CPM08N48te0
  - type: youtube
    url: https://youtu.be/Fr2807MvBHA
  - type: youtube
    url: https://youtu.be/BtX953SqPZM
  - type: youtube
    url: https://youtu.be/RDYYbi0gFsI

google_analytics: "UA-46465113-2"

# UI configs
title: "Portfolio by Andrew Gong"
subtitle: "See the world through my eyes!"
author: "Andrew Gong"
header:
 title: "Portfolio"
 subtitle: "by Andrew Gong"
footer:
 name: "Andrew Gong"
 bio: "I am a software developer and 3D animator currently studying Computer Science and Fine Arts (Animation & Moving Image) at the University of New South Wales. I specialise in combining technical and creative disciplines, with experience developing 3D applications using C++, DirectX, and Unreal Engine, alongside creating animation and assets in Maya and ZBrush."
 skills: "My background in graphics programming and computer graphics has given me a strong understanding of scripting and technical animation."
 awards: "As a two-time UNSW ADA Dean’s List recipient, I am driven by curiosity, a strong work ethic, and a commitment to continuous improvement."
web_design: "Andrew Gong"

social_urls:
  instagram: "https://www.instagram.com/andrew_x_gong/"
  linkedin: "https://www.linkedin.com/in/andrew-gong-17a059318/"
  github: "https://github.com/Kidudeman"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
